
name: ngrok
adopt-info: ngrok
summary: ngrok secure introspectable tunnels to localhost.
description: An instant, secure tunnel from a public URL to your localhost server through any NAT or firewall.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64le

parts:
  ngrok:
    plugin: dump
    source:
      - on amd64: https://bin.equinox.io/a/avYzMgGTC6e/ngrok-v3-3.10.1-linux-amd64.zip
      - on i386: https://bin.equinox.io/a/fDxyxMzoqK2/ngrok-v3-3.10.1-linux-386.zip
      - on armhf: https://bin.equinox.io/a/3i3T53unN8T/ngrok-v3-3.10.1-linux-arm.zip
      - on arm64: https://bin.equinox.io/a/ghcE1t39ymT/ngrok-v3-3.10.1-linux-arm64.zip
      - on s390x: https://bin.equinox.io/a/598JoTjWP8J/ngrok-v3-3.10.1-linux-s390x.zip
      - on ppc64le: https://bin.equinox.io/a/bH8UZg8wThD/ngrok-v3-3.10.1-linux-ppc64le.zip
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(./ngrok --version | cut -d " " -f 3)

plugs:
  ngrok-config:
    interface: personal-files
    write:
    - $HOME/.ngrok2

apps:
  ngrok:
    command: ngrok
    plugs: [network, network-bind, home, ngrok-config]
