name: ngrok
adopt-info: ngrok
summary: ngrok secure introspectable tunnels to localhost.
description: ngrok is a secure ingress platform that enables developers to add global server load balancing, reverse proxy, firewall, API gateway and Kubernetes Ingress to applications and APIs.

base: core24
grade: stable
confinement: strict

platforms:
  amd64:
  i386:
  armhf:
  arm64:
  s390x:

parts:
  ngrok:
    plugin: dump
    source:
      - on amd64: https://bin.equinox.io/a/cp4zbqoWWC1/ngrok-v3-3.19.1-linux-amd64.zip
      - on i386: https://bin.equinox.io/a/7RDEFXtBbAj/ngrok-v3-3.19.1-linux-386.zip
      - on armhf: https://bin.equinox.io/a/fB2XkincXBG/ngrok-v3-3.19.1-linux-arm.zip
      - on arm64: https://bin.equinox.io/a/96AhmnoTXuz/ngrok-v3-3.19.1-linux-arm64.zip
      - on s390x: https://bin.equinox.io/a/kLoGADrsu9d/ngrok-v3-3.19.1-linux-s390x.zip
    override-pull: |
      craftctl default
      craftctl set version=$(./ngrok --version | cut -d " " -f 3)

plugs:
  ngrok-config:
    interface: personal-files
    write:
      - $HOME/.ngrok2

apps:
  ngrok:
    command: ngrok
    plugs: [network, network-bind, home, ngrok-config]
