name: ngrok
adopt-info: ngrok
summary: ngrok secure introspectable tunnels to localhost.
description: ngrok is a secure ingress platform that enables developers to add global server load balancing, reverse proxy, firewall, API gateway and Kubernetes Ingress to applications and APIs.

base: core22
grade: stable
confinement: strict

architectures: # github actions uses amd64 as host architecture
  - build-on: [amd64]
  - build-for: amd64
  - build-for: i386
  - build-for: armhf
  - build-for: arm64
  - build-for: s390x

parts:
  ngrok:
    plugin: dump
    source:
      - on amd64 to amd64: https://bin.equinox.io/a/cp4zbqoWWC1/ngrok-v3-3.19.1-linux-amd64.zip
      - on amd64 to i386: https://bin.equinox.io/a/7RDEFXtBbAj/ngrok-v3-3.19.1-linux-386.zip
      - on amd64 to armhf: https://bin.equinox.io/a/fB2XkincXBG/ngrok-v3-3.19.1-linux-arm.zip
      - on amd64 to arm64: https://bin.equinox.io/a/96AhmnoTXuz/ngrok-v3-3.19.1-linux-arm64.zip
      - on amd64 to s390x: https://bin.equinox.io/a/kLoGADrsu9d/ngrok-v3-3.19.1-linux-s390x.zip
    override-pull: |
      craftctl default
      craftctl set version=$(./ngrok --version | cut -d " " -f 3)

plugs:
  ngrok-config:
    interface: personal-files
    write:
      - $HOME/.ngrok2

apps:
  ngrok:
    command: ngrok
    plugs: [network, network-bind, home, ngrok-config]
